//Autogenerated triple quantized liym file with draw function
int dandelion_seeding_seedstricount = 2;
f32 dandelion_seeding_seedsvertpos[] ATTRIBUTE_ALIGN(32) = {0.064326, -0.026735, -0.064326, -0.064326, -0.026735, 0.064326, -0.064326, -0.026735, -0.064326, 0.064326, -0.026735, 0.064326};
uint16_t dandelion_seeding_seedsvertposidx[] = {0, 1, 2, 0, 3, 1};
f32 dandelion_seeding_seedstexcord[] ATTRIBUTE_ALIGN(32) = {0.002434, -0.247566, 0.247566, -0.002434, 0.002434, -0.002434, 0.247566, -0.247566};
uint16_t dandelion_seeding_seedstexcordidx[] = {0, 1, 2, 0, 3, 1};

void ag_draw_dandelion_seeding_seeds(int vtxfmt) {
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, dandelion_seeding_seedstricount, vtxfmt,
		NULL, NULL, dandelion_seeding_seedsvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, dandelion_seeding_seedstexcordidx,
		NULL,
		NULL);
}