//Autogenerated triple quantized liym file with draw function
int buildingtranslittricount = 8;
f32 buildingtranslitvertpos[] ATTRIBUTE_ALIGN(32) = {-11.471391, 5.166181, 1.719071, -11.471391, 3.860440, 0.807040, -11.471391, 5.166181, 0.807040, -11.471391, 5.779357, 1.719071, -11.471391, 7.085097, 0.807040, -11.471391, 7.085097, 1.719071, -11.471391, 7.941317, 1.719071, -11.471391, 9.247057, 0.807040, -11.471391, 9.247057, 1.719071, -11.471391, 10.079116, 1.719071, -11.471391, 11.384855, 0.807040, -11.471391, 11.384855, 1.719071, -11.471391, 3.860440, 1.719071, -11.471391, 5.779357, 0.807040, -11.471391, 7.941317, 0.807040, -11.471391, 10.079116, 0.807040};
uint16_t buildingtranslitvertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 12, 1, 3, 13, 4, 6, 14, 7, 9, 15, 10};
f32 buildingtranslitvertnor[] ATTRIBUTE_ALIGN(32) = {1.000000, 0.000000, 0.000000};
uint16_t buildingtranslitvertnoridx[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
f32 buildingtranslittexcord[] ATTRIBUTE_ALIGN(32) = {0.504624, 0.820567, 0.748015, 0.997196, 0.504624, 0.997196, 0.748015, 0.820567};
uint16_t buildingtranslittexcordidx[] = {0, 1, 2, 3, 2, 0, 3, 2, 0, 3, 2, 0, 0, 3, 1, 3, 1, 2, 3, 1, 2, 3, 1, 2};

void ag_draw_buildingtranslit(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &buildingtranslitvertpos[0], 12);
	GX_SetArray(GX_VA_NRM, &buildingtranslitvertnor[0], 12);
	GX_SetArray(GX_VA_TEX0, &buildingtranslittexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_VNIDX16 | LV_TCIDX16, buildingtranslittricount, vtxfmt,
		NULL, NULL, buildingtranslitvertposidx,
		NULL, NULL, buildingtranslitvertnoridx,
		NULL, NULL, buildingtranslittexcordidx,
		NULL,
		NULL);
}