//Autogenerated triple quantized liym file with draw function
int chainlinktricount = 4;
f32 chainlinkvertpos[] ATTRIBUTE_ALIGN(32) = {-15.259787, 2.898733, 0.124544, -15.259787, -11.464397, 1.711662, -15.259787, -11.464397, 0.124544, -15.259787, 23.453411, 0.124544, -15.259787, 13.222493, 1.711662, -15.259787, 13.222493, 0.124544, -15.259787, 2.898733, 1.711662, -15.259787, 23.453411, 1.711662};
uint16_t chainlinkvertposidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 1, 3, 7, 4};
f32 chainlinktexcord[] ATTRIBUTE_ALIGN(32) = {61.091843, 8.320312, -60.076218, -7.679687, -60.076218, 8.320312, 43.782120, 8.320312, -42.766495, -7.679687, -42.766495, 8.320312, 61.091843, -7.679688, 43.782120, -7.679688};
uint16_t chainlinktexcordidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 1, 3, 7, 4};

void ag_draw_chainlink(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &chainlinkvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &chainlinktexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, chainlinktricount, vtxfmt,
		NULL, NULL, chainlinkvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, chainlinktexcordidx,
		NULL,
		NULL);
}